/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardLivraisonRouteImport } from './routes/dashboard/livraison'
import { Route as DashboardCommandeRouteImport } from './routes/dashboard/commande'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as HomeSalePointRouteImport } from './routes/_home/salePoint'
import { Route as HomePanierRouteImport } from './routes/_home/panier'
import { Route as HomeEspaceRevRouteImport } from './routes/_home/espace-rev'
import { Route as HomeContactRouteImport } from './routes/_home/contact'
import { Route as HomeBoutiqueRouteImport } from './routes/_home/boutique'
import { Route as HomeBlogRouteImport } from './routes/_home/blog'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as HomeProduitProductIdRouteImport } from './routes/_home/produit/$productId'
import { Route as HomeLegalRemboursementRouteImport } from './routes/_home/legal/remboursement'
import { Route as HomeLegalPrivacyRouteImport } from './routes/_home/legal/privacy'
import { Route as HomeLegalMentionsLegalesRouteImport } from './routes/_home/legal/mentions-legales'
import { Route as HomeLegalLivraisonRouteImport } from './routes/_home/legal/livraison'
import { Route as HomeLegalFaqRouteImport } from './routes/_home/legal/faq'
import { Route as HomeLegalCookiesRouteImport } from './routes/_home/legal/cookies'
import { Route as HomeLegalCgvRouteImport } from './routes/_home/legal/cgv'
import { Route as HomeLegalCguRouteImport } from './routes/_home/legal/cgu'

const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLivraisonRoute = DashboardLivraisonRouteImport.update({
  id: '/dashboard/livraison',
  path: '/dashboard/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCommandeRoute = DashboardCommandeRouteImport.update({
  id: '/dashboard/commande',
  path: '/dashboard/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSalePointRoute = HomeSalePointRouteImport.update({
  id: '/salePoint',
  path: '/salePoint',
  getParentRoute: () => HomeRoute,
} as any)
const HomePanierRoute = HomePanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => HomeRoute,
} as any)
const HomeEspaceRevRoute = HomeEspaceRevRouteImport.update({
  id: '/espace-rev',
  path: '/espace-rev',
  getParentRoute: () => HomeRoute,
} as any)
const HomeContactRoute = HomeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HomeRoute,
} as any)
const HomeBoutiqueRoute = HomeBoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => HomeRoute,
} as any)
const HomeBlogRoute = HomeBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProduitProductIdRoute = HomeProduitProductIdRouteImport.update({
  id: '/produit/$productId',
  path: '/produit/$productId',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLegalRemboursementRoute = HomeLegalRemboursementRouteImport.update({
  id: '/legal/remboursement',
  path: '/legal/remboursement',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLegalPrivacyRoute = HomeLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLegalMentionsLegalesRoute =
  HomeLegalMentionsLegalesRouteImport.update({
    id: '/legal/mentions-legales',
    path: '/legal/mentions-legales',
    getParentRoute: () => HomeRoute,
  } as any)
const HomeLegalLivraisonRoute = HomeLegalLivraisonRouteImport.update({
  id: '/legal/livraison',
  path: '/legal/livraison',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLegalFaqRoute = HomeLegalFaqRouteImport.update({
  id: '/legal/faq',
  path: '/legal/faq',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLegalCookiesRoute = HomeLegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLegalCgvRoute = HomeLegalCgvRouteImport.update({
  id: '/legal/cgv',
  path: '/legal/cgv',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLegalCguRoute = HomeLegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/paiement': typeof PaiementRoute
  '/about': typeof HomeAboutRoute
  '/blog': typeof HomeBlogRoute
  '/boutique': typeof HomeBoutiqueRoute
  '/contact': typeof HomeContactRoute
  '/espace-rev': typeof HomeEspaceRevRoute
  '/panier': typeof HomePanierRoute
  '/salePoint': typeof HomeSalePointRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/commande': typeof DashboardCommandeRoute
  '/dashboard/livraison': typeof DashboardLivraisonRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/legal/cgu': typeof HomeLegalCguRoute
  '/legal/cgv': typeof HomeLegalCgvRoute
  '/legal/cookies': typeof HomeLegalCookiesRoute
  '/legal/faq': typeof HomeLegalFaqRoute
  '/legal/livraison': typeof HomeLegalLivraisonRoute
  '/legal/mentions-legales': typeof HomeLegalMentionsLegalesRoute
  '/legal/privacy': typeof HomeLegalPrivacyRoute
  '/legal/remboursement': typeof HomeLegalRemboursementRoute
  '/produit/$productId': typeof HomeProduitProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/paiement': typeof PaiementRoute
  '/about': typeof HomeAboutRoute
  '/blog': typeof HomeBlogRoute
  '/boutique': typeof HomeBoutiqueRoute
  '/contact': typeof HomeContactRoute
  '/espace-rev': typeof HomeEspaceRevRoute
  '/panier': typeof HomePanierRoute
  '/salePoint': typeof HomeSalePointRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/commande': typeof DashboardCommandeRoute
  '/dashboard/livraison': typeof DashboardLivraisonRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/legal/cgu': typeof HomeLegalCguRoute
  '/legal/cgv': typeof HomeLegalCgvRoute
  '/legal/cookies': typeof HomeLegalCookiesRoute
  '/legal/faq': typeof HomeLegalFaqRoute
  '/legal/livraison': typeof HomeLegalLivraisonRoute
  '/legal/mentions-legales': typeof HomeLegalMentionsLegalesRoute
  '/legal/privacy': typeof HomeLegalPrivacyRoute
  '/legal/remboursement': typeof HomeLegalRemboursementRoute
  '/produit/$productId': typeof HomeProduitProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_home': typeof HomeRouteWithChildren
  '/paiement': typeof PaiementRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/blog': typeof HomeBlogRoute
  '/_home/boutique': typeof HomeBoutiqueRoute
  '/_home/contact': typeof HomeContactRoute
  '/_home/espace-rev': typeof HomeEspaceRevRoute
  '/_home/panier': typeof HomePanierRoute
  '/_home/salePoint': typeof HomeSalePointRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/commande': typeof DashboardCommandeRoute
  '/dashboard/livraison': typeof DashboardLivraisonRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/_home/legal/cgu': typeof HomeLegalCguRoute
  '/_home/legal/cgv': typeof HomeLegalCgvRoute
  '/_home/legal/cookies': typeof HomeLegalCookiesRoute
  '/_home/legal/faq': typeof HomeLegalFaqRoute
  '/_home/legal/livraison': typeof HomeLegalLivraisonRoute
  '/_home/legal/mentions-legales': typeof HomeLegalMentionsLegalesRoute
  '/_home/legal/privacy': typeof HomeLegalPrivacyRoute
  '/_home/legal/remboursement': typeof HomeLegalRemboursementRoute
  '/_home/produit/$productId': typeof HomeProduitProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/paiement'
    | '/about'
    | '/blog'
    | '/boutique'
    | '/contact'
    | '/espace-rev'
    | '/panier'
    | '/salePoint'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/dashboard/commande'
    | '/dashboard/livraison'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/cookies'
    | '/legal/faq'
    | '/legal/livraison'
    | '/legal/mentions-legales'
    | '/legal/privacy'
    | '/legal/remboursement'
    | '/produit/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/paiement'
    | '/about'
    | '/blog'
    | '/boutique'
    | '/contact'
    | '/espace-rev'
    | '/panier'
    | '/salePoint'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/dashboard/commande'
    | '/dashboard/livraison'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/cookies'
    | '/legal/faq'
    | '/legal/livraison'
    | '/legal/mentions-legales'
    | '/legal/privacy'
    | '/legal/remboursement'
    | '/produit/$productId'
  id:
    | '__root__'
    | '/'
    | '/_home'
    | '/paiement'
    | '/_home/about'
    | '/_home/blog'
    | '/_home/boutique'
    | '/_home/contact'
    | '/_home/espace-rev'
    | '/_home/panier'
    | '/_home/salePoint'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/dashboard/commande'
    | '/dashboard/livraison'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/_home/legal/cgu'
    | '/_home/legal/cgv'
    | '/_home/legal/cookies'
    | '/_home/legal/faq'
    | '/_home/legal/livraison'
    | '/_home/legal/mentions-legales'
    | '/_home/legal/privacy'
    | '/_home/legal/remboursement'
    | '/_home/produit/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  PaiementRoute: typeof PaiementRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DashboardCommandeRoute: typeof DashboardCommandeRoute
  DashboardLivraisonRoute: typeof DashboardLivraisonRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/livraison': {
      id: '/dashboard/livraison'
      path: '/dashboard/livraison'
      fullPath: '/dashboard/livraison'
      preLoaderRoute: typeof DashboardLivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/commande': {
      id: '/dashboard/commande'
      path: '/dashboard/commande'
      fullPath: '/dashboard/commande'
      preLoaderRoute: typeof DashboardCommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/salePoint': {
      id: '/_home/salePoint'
      path: '/salePoint'
      fullPath: '/salePoint'
      preLoaderRoute: typeof HomeSalePointRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/panier': {
      id: '/_home/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof HomePanierRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/espace-rev': {
      id: '/_home/espace-rev'
      path: '/espace-rev'
      fullPath: '/espace-rev'
      preLoaderRoute: typeof HomeEspaceRevRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/contact': {
      id: '/_home/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof HomeContactRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/boutique': {
      id: '/_home/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof HomeBoutiqueRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/blog': {
      id: '/_home/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof HomeBlogRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/produit/$productId': {
      id: '/_home/produit/$productId'
      path: '/produit/$productId'
      fullPath: '/produit/$productId'
      preLoaderRoute: typeof HomeProduitProductIdRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/legal/remboursement': {
      id: '/_home/legal/remboursement'
      path: '/legal/remboursement'
      fullPath: '/legal/remboursement'
      preLoaderRoute: typeof HomeLegalRemboursementRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/legal/privacy': {
      id: '/_home/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof HomeLegalPrivacyRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/legal/mentions-legales': {
      id: '/_home/legal/mentions-legales'
      path: '/legal/mentions-legales'
      fullPath: '/legal/mentions-legales'
      preLoaderRoute: typeof HomeLegalMentionsLegalesRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/legal/livraison': {
      id: '/_home/legal/livraison'
      path: '/legal/livraison'
      fullPath: '/legal/livraison'
      preLoaderRoute: typeof HomeLegalLivraisonRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/legal/faq': {
      id: '/_home/legal/faq'
      path: '/legal/faq'
      fullPath: '/legal/faq'
      preLoaderRoute: typeof HomeLegalFaqRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/legal/cookies': {
      id: '/_home/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof HomeLegalCookiesRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/legal/cgv': {
      id: '/_home/legal/cgv'
      path: '/legal/cgv'
      fullPath: '/legal/cgv'
      preLoaderRoute: typeof HomeLegalCgvRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/legal/cgu': {
      id: '/_home/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof HomeLegalCguRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeBlogRoute: typeof HomeBlogRoute
  HomeBoutiqueRoute: typeof HomeBoutiqueRoute
  HomeContactRoute: typeof HomeContactRoute
  HomeEspaceRevRoute: typeof HomeEspaceRevRoute
  HomePanierRoute: typeof HomePanierRoute
  HomeSalePointRoute: typeof HomeSalePointRoute
  HomeLegalCguRoute: typeof HomeLegalCguRoute
  HomeLegalCgvRoute: typeof HomeLegalCgvRoute
  HomeLegalCookiesRoute: typeof HomeLegalCookiesRoute
  HomeLegalFaqRoute: typeof HomeLegalFaqRoute
  HomeLegalLivraisonRoute: typeof HomeLegalLivraisonRoute
  HomeLegalMentionsLegalesRoute: typeof HomeLegalMentionsLegalesRoute
  HomeLegalPrivacyRoute: typeof HomeLegalPrivacyRoute
  HomeLegalRemboursementRoute: typeof HomeLegalRemboursementRoute
  HomeProduitProductIdRoute: typeof HomeProduitProductIdRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeBlogRoute: HomeBlogRoute,
  HomeBoutiqueRoute: HomeBoutiqueRoute,
  HomeContactRoute: HomeContactRoute,
  HomeEspaceRevRoute: HomeEspaceRevRoute,
  HomePanierRoute: HomePanierRoute,
  HomeSalePointRoute: HomeSalePointRoute,
  HomeLegalCguRoute: HomeLegalCguRoute,
  HomeLegalCgvRoute: HomeLegalCgvRoute,
  HomeLegalCookiesRoute: HomeLegalCookiesRoute,
  HomeLegalFaqRoute: HomeLegalFaqRoute,
  HomeLegalLivraisonRoute: HomeLegalLivraisonRoute,
  HomeLegalMentionsLegalesRoute: HomeLegalMentionsLegalesRoute,
  HomeLegalPrivacyRoute: HomeLegalPrivacyRoute,
  HomeLegalRemboursementRoute: HomeLegalRemboursementRoute,
  HomeProduitProductIdRoute: HomeProduitProductIdRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  PaiementRoute: PaiementRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  DashboardCommandeRoute: DashboardCommandeRoute,
  DashboardLivraisonRoute: DashboardLivraisonRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
