/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeSettingRouteImport } from './routes/_home/setting'
import { Route as HomeUsersRouteImport } from './routes/_home/Users'
import { Route as HomeProductsRouteImport } from './routes/_home/Products'
import { Route as HomePaymentsRouteImport } from './routes/_home/Payments'
import { Route as HomeOrdersRouteImport } from './routes/_home/Orders'
import { Route as HomeMarketingRouteImport } from './routes/_home/Marketing'
import { Route as HomeDeliveriesRouteImport } from './routes/_home/Deliveries'
import { Route as HomeDashboardRouteImport } from './routes/_home/Dashboard'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSettingRoute = HomeSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => HomeRoute,
} as any)
const HomeUsersRoute = HomeUsersRouteImport.update({
  id: '/Users',
  path: '/Users',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProductsRoute = HomeProductsRouteImport.update({
  id: '/Products',
  path: '/Products',
  getParentRoute: () => HomeRoute,
} as any)
const HomePaymentsRoute = HomePaymentsRouteImport.update({
  id: '/Payments',
  path: '/Payments',
  getParentRoute: () => HomeRoute,
} as any)
const HomeOrdersRoute = HomeOrdersRouteImport.update({
  id: '/Orders',
  path: '/Orders',
  getParentRoute: () => HomeRoute,
} as any)
const HomeMarketingRoute = HomeMarketingRouteImport.update({
  id: '/Marketing',
  path: '/Marketing',
  getParentRoute: () => HomeRoute,
} as any)
const HomeDeliveriesRoute = HomeDeliveriesRouteImport.update({
  id: '/Deliveries',
  path: '/Deliveries',
  getParentRoute: () => HomeRoute,
} as any)
const HomeDashboardRoute = HomeDashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Dashboard': typeof HomeDashboardRoute
  '/Deliveries': typeof HomeDeliveriesRoute
  '/Marketing': typeof HomeMarketingRoute
  '/Orders': typeof HomeOrdersRoute
  '/Payments': typeof HomePaymentsRoute
  '/Products': typeof HomeProductsRoute
  '/Users': typeof HomeUsersRoute
  '/setting': typeof HomeSettingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Dashboard': typeof HomeDashboardRoute
  '/Deliveries': typeof HomeDeliveriesRoute
  '/Marketing': typeof HomeMarketingRoute
  '/Orders': typeof HomeOrdersRoute
  '/Payments': typeof HomePaymentsRoute
  '/Products': typeof HomeProductsRoute
  '/Users': typeof HomeUsersRoute
  '/setting': typeof HomeSettingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_home': typeof HomeRouteWithChildren
  '/_home/Dashboard': typeof HomeDashboardRoute
  '/_home/Deliveries': typeof HomeDeliveriesRoute
  '/_home/Marketing': typeof HomeMarketingRoute
  '/_home/Orders': typeof HomeOrdersRoute
  '/_home/Payments': typeof HomePaymentsRoute
  '/_home/Products': typeof HomeProductsRoute
  '/_home/Users': typeof HomeUsersRoute
  '/_home/setting': typeof HomeSettingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Dashboard'
    | '/Deliveries'
    | '/Marketing'
    | '/Orders'
    | '/Payments'
    | '/Products'
    | '/Users'
    | '/setting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Dashboard'
    | '/Deliveries'
    | '/Marketing'
    | '/Orders'
    | '/Payments'
    | '/Products'
    | '/Users'
    | '/setting'
  id:
    | '__root__'
    | '/'
    | '/_home'
    | '/_home/Dashboard'
    | '/_home/Deliveries'
    | '/_home/Marketing'
    | '/_home/Orders'
    | '/_home/Payments'
    | '/_home/Products'
    | '/_home/Users'
    | '/_home/setting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/setting': {
      id: '/_home/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof HomeSettingRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/Users': {
      id: '/_home/Users'
      path: '/Users'
      fullPath: '/Users'
      preLoaderRoute: typeof HomeUsersRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/Products': {
      id: '/_home/Products'
      path: '/Products'
      fullPath: '/Products'
      preLoaderRoute: typeof HomeProductsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/Payments': {
      id: '/_home/Payments'
      path: '/Payments'
      fullPath: '/Payments'
      preLoaderRoute: typeof HomePaymentsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/Orders': {
      id: '/_home/Orders'
      path: '/Orders'
      fullPath: '/Orders'
      preLoaderRoute: typeof HomeOrdersRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/Marketing': {
      id: '/_home/Marketing'
      path: '/Marketing'
      fullPath: '/Marketing'
      preLoaderRoute: typeof HomeMarketingRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/Deliveries': {
      id: '/_home/Deliveries'
      path: '/Deliveries'
      fullPath: '/Deliveries'
      preLoaderRoute: typeof HomeDeliveriesRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/Dashboard': {
      id: '/_home/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof HomeDashboardRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeDashboardRoute: typeof HomeDashboardRoute
  HomeDeliveriesRoute: typeof HomeDeliveriesRoute
  HomeMarketingRoute: typeof HomeMarketingRoute
  HomeOrdersRoute: typeof HomeOrdersRoute
  HomePaymentsRoute: typeof HomePaymentsRoute
  HomeProductsRoute: typeof HomeProductsRoute
  HomeUsersRoute: typeof HomeUsersRoute
  HomeSettingRoute: typeof HomeSettingRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeDashboardRoute: HomeDashboardRoute,
  HomeDeliveriesRoute: HomeDeliveriesRoute,
  HomeMarketingRoute: HomeMarketingRoute,
  HomeOrdersRoute: HomeOrdersRoute,
  HomePaymentsRoute: HomePaymentsRoute,
  HomeProductsRoute: HomeProductsRoute,
  HomeUsersRoute: HomeUsersRoute,
  HomeSettingRoute: HomeSettingRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
